Adding WELON
SinglePoolAlliance/Registration pull request #107
Opened 2021-02-17 23:20 UTC by jbarros35

2021-02-21 18:19 UTC, leo42 requested changes

2021-02-21 18:19 UTC, leo42 commented on registry.json
> +    "operatorName": "Wise Capital",
Please use a real name o live empty.

2021-02-22 22:22 UTC, jbarros35 reviewed
updated name.

2021-02-22 22:22 UTC, closed without merging

2021-02-22 22:22 UTC, jbarros35 commented
due to conflicts I should submit again my PR.