Adding MMA Stake Pool
SinglePoolAlliance/Registration pull request #115
Opened 2021-02-24 16:14 UTC by MMA-stakepool

2021-03-02 15:55 UTC, leo42 requested changes

2021-03-02 15:55 UTC, leo42 commented on registry.json
> +    "telegram": "Hans [MMA]",
Username not found.

2021-03-21 21:16 UTC, kiriakos commented
@MMA-stakepool can you give us a valid private telegram handle? Otherwise we can't add you to the SPA

2021-03-28 16:33 UTC, SinglePoolAlliance approved these changes

2021-03-28 16:36 UTC, merged