+ SEAL
SinglePoolAlliance/Registration pull request #126
Opened 2021-03-03 23:41 UTC by benapetr

2021-03-13 07:26 UTC, leo42 requested changes

2021-03-13 07:26 UTC, leo42 commented on registry.json
> +      "youtube": ""
We require at least one active Social media Account.

2021-03-19 13:05 UTC, leo42 requested changes

2021-03-28 16:23 UTC, SinglePoolAlliance approved these changes

2021-03-28 16:25 UTC, SinglePoolAlliance approved these changes

2021-03-28 16:27 UTC, merged