Update registry.json
SinglePoolAlliance/Registration pull request #180
Opened 2021-04-02 06:16 UTC by IvanLee113

Added Echo Pool 
pool1wrt4jvd6nsxxtjws5lzl54zdjj8793u9jumcltqhsyqcgaa9d52
https://cardano-echo-pool.com/

2021-04-09 02:38 UTC, lophre commented on registry.json
> +      "poolId":"pool1wrt4jvd6nsxxtjws5lzl54zdjj8793u9jumcltqhsyqcgaa9d52",
This is not a valid poolid (adapools id).  Your poolid is 70d75931ba9c0c65c9d0a7c5fa544d948fe2c78597378fac17810184

2021-04-09 02:41 UTC, lophre requested changes
Please update your poolid.

2021-04-09 04:12 UTC, IvanLee113 commented
Hello Lophre, 

There could be syntax error during the check, could you assist me? and also I have updated the pool ID, please advise. Thank you.

2021-04-11 00:41 UTC, lophre commented
You have two successive curly braces... No problem, I will edit and merge.

2021-04-11 00:44 UTC, lophre approved these changes

2021-04-11 00:44 UTC, merged