Creating LOKI
SinglePoolAlliance/Registration pull request #214
Opened 2021-04-12 17:02 UTC by CoderFX

2021-05-01 11:20 UTC, leo42 requested changes

2021-05-01 11:20 UTC, leo42 commented on registry.json
> +      "operatorName":"Captain Ahab",
Please use a real name or leave empty

2021-06-06 15:20 UTC, Bez625 requested changes

2021-06-06 15:20 UTC, Bez625 commented on registry.json
> +      "poolId":"pool17j94qfcxvr0xvuz5xl2c8nnt8pcv4v2d753vfxx3p4l4sukhtq0",
Please can you change this to your pool id, e.g. f758bd7d92dec6dc5a7f23ad20bf53d4dcf76c1ed84c0449289cfc8b

2021-06-06 15:21 UTC, Bez625 commented
@CoderFX This has been open a while - please can you address the comments? If we dont hear from you we will close

2021-06-16 07:38 UTC, closed without merging