GOAL pool registration
SinglePoolAlliance/Registration pull request #221
Opened 2021-04-14 10:21 UTC by dmlebany

2021-05-01 11:39 UTC, leo42 requested changes

2021-05-01 11:39 UTC, leo42 commented on registry.json
> +       "youtube":""
We need at least one social media

2021-05-03 11:29 UTC, dmlebany commented on registry.json
> +       "twitter":"",
```suggestion
       "twitter":"https://twitter.com/goal_pool",
```

2021-05-03 11:30 UTC, dmlebany commented on registry.json
> +       "youtube":""
@leo42 Added twitter account.

2021-06-02 15:45 UTC, leo42 requested changes

2021-06-02 15:45 UTC, leo42 commented on registry.json
> +    "poolId":"pool109ee6weyn52awvu30gspwmp6xwws98z0dhzcw2dqupc6vv6mkg6",
poolID = 79739d3b249d15d733917a20176c3a339d029c4f6dc58729a0e071a6

2021-06-02 15:51 UTC, nikolaypavlov commented on registry.json
> +    "poolId":"pool109ee6weyn52awvu30gspwmp6xwws98z0dhzcw2dqupc6vv6mkg6",
```suggestion
    "poolId":"79739d3b249d15d733917a20176c3a339d029c4f6dc58729a0e071a6",
```

2021-06-02 15:52 UTC, nikolaypavlov commented on registry.json
> +    "poolId":"pool109ee6weyn52awvu30gspwmp6xwws98z0dhzcw2dqupc6vv6mkg6",
```suggestion
    "poolId":"79739d3b249d15d733917a20176c3a339d029c4f6dc58729a0e071a6",
```

2021-06-02 15:58 UTC, dmlebany commented on registry.json
> +    "poolId":"pool109ee6weyn52awvu30gspwmp6xwws98z0dhzcw2dqupc6vv6mkg6",
Fixed pool id

2021-06-02 19:06 UTC, dmlebany commented
There is bunch of conflicts here that I'm not sure how to solve. I'm going to create a new PR with all the recent changes.

2021-06-02 19:06 UTC, closed without merging