Request membership of our pool into single pool alliance!
SinglePoolAlliance/Registration pull request #225
Opened 2021-04-16 19:47 UTC by drunkbad

2021-05-01 11:46 UTC, leo42 requested changes

2021-05-01 11:46 UTC, leo42 commented on registry.json
> +         "youtube":""
We need at least one active social media.

2021-06-06 15:22 UTC, Bez625 commented
@drunkbad please can you update this PR or we will close? Thanks

2021-06-07 20:19 UTC, Bez625 approved these changes

2021-06-07 20:20 UTC, merged