Update registry.json
SinglePoolAlliance/Registration pull request #228
Opened 2021-04-18 07:46 UTC by dockrieger86

Registry request for ANVIL Pool

2021-04-21 20:34 UTC, dockrieger86 commented
hi, just wanted to see if my registration request has gone through or if I need to change something.
THanks

2021-05-01 11:52 UTC, leo42 requested changes

2021-05-01 11:52 UTC, leo42 commented on registry.json
> +    "telegram":"",
We need a active personal telegram handle (no groups or pages)

2021-06-06 15:22 UTC, Bez625 commented
@dockrieger86 please can you update this PR or we will close? Thanks

2021-06-16 07:38 UTC, Bez625 commented
Closing as we believe this pool was renamed any way

2021-06-16 07:38 UTC, closed without merging