coudrebros.eu - update registry.json
SinglePoolAlliance/Registration pull request #238
Opened 2021-04-29 20:41 UTC by Couder82

2021-05-01 12:15 UTC, leo42 requested changes

2021-05-01 12:15 UTC, leo42 commented on registry.json
> +    "operatorName":"Couder",
Please use a real name o leave empty.

2021-05-03 07:22 UTC, Couder82 commented on registry.json
> +    "operatorName":"Couder",
OK, changed.

2021-05-30 14:45 UTC, leo42 approved these changes

2021-05-30 14:46 UTC, merged