Adding Gibon pool
SinglePoolAlliance/Registration pull request #259
Opened 2021-05-16 11:56 UTC by gibonada

2021-05-30 15:02 UTC, leo42 requested changes

2021-05-30 15:02 UTC, leo42 commented on registry.json
> +      "telegram":"https://t.me/gibonpool",
We need a user telegram handle, no groups of channels please. this is for voting purpose's.

2021-06-04 20:17 UTC, gibonada reviewed
Updating my telegram handle

2021-06-04 20:31 UTC, closed without merging

2021-06-04 20:47 UTC, gibonada commented
Hi, I hope I update it, my telegram handle is @GibonAda, thanks.
Have a nice day Paul.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
neděle 30. květen 2021 17:02, leo42 ***@***.***> napsal:

> @leo42 requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [registry.json](https://github.com/SinglePoolAlliance/Registration/pull/259#discussion_r642089021):
>
>> @@ -1,4 +1,19 @@
>  [
> +  {
> +      "ticker":"GIBON",
> +      "poolId":"b352315bd54d61dfcd8fd78a2aa4f3e0cc8ef342b9495465b0b0b2ce",
> +      "social":{
> +         "facebook":"",
> +         ***@***.***_pool",
> +         "website":"https://gibon.online",
> +         "reddit":"",
> +         "instagram":"",
> +         "youtube":""
> +      },
> +      "telegram":"https://t.me/gibonpool",
>
> We need a user telegram handle, no groups of channels please. this is for voting purpose's.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/SinglePoolAlliance/Registration/pull/259#pullrequestreview-671839165), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ATQGXV3RZRLA55B7J4IGQ5DTQJHRDANCNFSM446ZOCJA).

2021-06-06 09:06 UTC, gibonada commented
Hi Leo,
could you please add my pool to registry? Its no longer on the list.
{

"ticker":"GIBON",

"poolId":"b352315bd54d61dfcd8fd78a2aa4f3e0cc8ef342b9495465b0b0b2ce",

"social":{

"facebook":"",

***@***.***_pool",

"website":"https://gibon.online",

"reddit":"",

"instagram":"",

"youtube":""

},

"telegram":"@GibonAda",

"operatorName":"Paul",

"github":""

},
I cannot merge it, and it always conflicting. Thank you very much. Paul.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
pátek 4. červen 2021 22:47, Pavel Vahala ***@***.***> napsal:

> Hi, I hope I update it, my telegram handle is @GibonAda, thanks.
> Have a nice day Paul.
>
> Sent with [ProtonMail](https://protonmail.com) Secure Email.
>
> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> neděle 30. květen 2021 17:02, leo42 ***@***.***> napsal:
>
>> @leo42 requested changes on this pull request.
>>
>> ---------------------------------------------------------------
>>
>> In [registry.json](https://github.com/SinglePoolAlliance/Registration/pull/259#discussion_r642089021):
>>
>>> @@ -1,4 +1,19 @@
>>  [
>> +  {
>> +      "ticker":"GIBON",
>> +      "poolId":"b352315bd54d61dfcd8fd78a2aa4f3e0cc8ef342b9495465b0b0b2ce",
>> +      "social":{
>> +         "facebook":"",
>> +         ***@***.***_pool",
>> +         "website":"https://gibon.online",
>> +         "reddit":"",
>> +         "instagram":"",
>> +         "youtube":""
>> +      },
>> +      "telegram":"https://t.me/gibonpool",
>>
>> We need a user telegram handle, no groups of channels please. this is for voting purpose's.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, [view it on GitHub](https://github.com/SinglePoolAlliance/Registration/pull/259#pullrequestreview-671839165), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ATQGXV3RZRLA55B7J4IGQ5DTQJHRDANCNFSM446ZOCJA).