Adding MOAI pool
SinglePoolAlliance/Registration pull request #269
Opened 2021-05-24 10:01 UTC by moaipool

Thanks :)

2021-05-30 15:36 UTC, leo42 requested changes

2021-05-30 15:36 UTC, leo42 commented on registry.json
> +      "telegram":"MoaiPool",
Username not found.

2021-06-05 18:31 UTC, Bez625 requested changes

2021-06-05 18:31 UTC, Bez625 commented on registry.json
> +         "instagram":""
Please add `"youtube":""` this is a required property

2021-06-05 19:22 UTC, merged