Registering Piggy Bank
SinglePoolAlliance/Registration pull request #270
Opened 2021-05-25 15:27 UTC by ada-piggy-bank

2021-05-30 15:40 UTC, leo42 requested changes

2021-05-30 15:40 UTC, leo42 commented on adapools.json
>        }
Please do not make changed to the adapools.json file. this file is automatically generated.

2021-06-06 15:26 UTC, Bez625 commented
@ada-piggy-bank Please can you address the review comments?

2021-06-11 08:35 UTC, Bez625 approved these changes
I'm going to approve even though there is a (hopefully insignificant) change to adapools.json. If it breaks the website ill fix.

2021-06-11 08:40 UTC, merged