Update registry.json
SinglePoolAlliance/Registration pull request #285
Opened 2021-06-03 19:05 UTC by zeldapool-ada-pool

Added Z3LDA pool

2021-06-05 17:56 UTC, Bez625 requested changes
Please address the comments

2021-06-05 17:56 UTC, Bez625 commented on registry.json
> +            "website": "https://www.facebook.com/z3ldastakingpool",
This should be your personal website - please leave empty or add a website

2021-06-05 17:56 UTC, Bez625 commented on registry.json
> +            "twitter": "Z3ldaP",
This account has been suspended. If you no longer plan on using it please can you remove from the PR?

2021-06-05 17:56 UTC, Bez625 commented on registry.json
> +        "telegram": "z3ldastakepooll",
This could not be found. It should be a users telegram handle - not the name of a group / page.

2021-06-05 17:56 UTC, Bez625 commented on registry.json
> +        "operatorName": "Beej",
Please can you change to your real first name, real full name or leave blank?

2021-06-05 17:56 UTC, Bez625 commented on registry.json
> +            "facebook": "https://www.facebook.com/z3ldastakingpool",
There is no content on this fb page - please could you show some activity?

2021-06-16 07:45 UTC, Bez625 commented
@zeldapool-ada-pool Please can you address the comments if you still want to be added?

2021-06-25 07:27 UTC, Bez625 commented
@zeldapool-ada-pool if we dont hear from you soon we will close the PR

2021-06-30 16:47 UTC, Bez625 commented
Closing as there has been no update recently. Please open a new PR if you wish to be added

2021-06-30 16:47 UTC, closed without merging

2021-06-30 16:57 UTC, zeldapool-ada-pool commented
Apologies I’ve been snowed under. Thanks 

Sent from my iPhone

> On Jun 30, 2021, at 12:48 PM, Chris Berry ***@***.***> wrote:
> 
> ﻿
> Closing as there has been no update recently. Please open a new PR if you wish to be added
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.