ALICE Stake Pool Registration
SinglePoolAlliance/Registration pull request #293
Opened 2021-06-07 21:08 UTC by SkiLov3

2021-06-08 07:42 UTC, Bez625 requested changes

2021-06-08 07:42 UTC, Bez625 commented on registry.json
> +      "twitter": "StakeAlice",
Please could we see some more activity on social media?

2021-06-08 13:12 UTC, SkiLov3 commented
Absolutely sorry on call this week and last can do in the next few days.

On Tue, Jun 8, 2021, 12:42 AM Chris Berry ***@***.***> wrote:

> *@Bez625* requested changes on this pull request.
> ------------------------------
>
> In registry.json
> <https://github.com/SinglePoolAlliance/Registration/pull/293#discussion_r647194223>
> :
>
> > @@ -2924,5 +2924,20 @@
>      "telegram": "Hayes7777",
>      "operatorName": "Steven",
>      "github": ""
> +  },
> + {
> +    "ticker": "ALICE",
> +    "poolId": "1c220012e987c342ec4b4c6cea04501d0cf003459804b0e7018d3c73",
> +    "social": {
> +      "twitter": "StakeAlice",
>
> Please could we see some more activity on social media?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SinglePoolAlliance/Registration/pull/293#pullrequestreview-678192256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALIP3OHWMXXE374WZXGOABDTRXCXTANCNFSM46IPJJWA>
> .
>

2021-06-08 13:16 UTC, Bez625 commented
No worries, maybe add a comment on here when you've had time to be a bit more active and then we can review again.

Thanks!

2021-06-08 13:41 UTC, SkiLov3 commented
Will do,

I'll circle back in a couple days.

On Tue, Jun 8, 2021, 6:16 AM Chris Berry ***@***.***> wrote:

> No worries, maybe add a comment on here when you've had time to be a bit
> more active and then we can review again.
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SinglePoolAlliance/Registration/pull/293#issuecomment-856758218>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALIP3OGGM5ZY2KOOINY7BDTTRYJ4DANCNFSM46IPJJWA>
> .
>

2021-06-10 15:19 UTC, SkiLov3 commented
Hey Chris,

I have been much more active on Twitter if you would give my registration
another consideration.

On Tue, Jun 8, 2021, 6:41 AM Nik Marsh ***@***.***> wrote:

> Will do,
>
> I'll circle back in a couple days.
>
> On Tue, Jun 8, 2021, 6:16 AM Chris Berry ***@***.***> wrote:
>
>> No worries, maybe add a comment on here when you've had time to be a bit
>> more active and then we can review again.
>>
>> Thanks!
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/SinglePoolAlliance/Registration/pull/293#issuecomment-856758218>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALIP3OGGM5ZY2KOOINY7BDTTRYJ4DANCNFSM46IPJJWA>
>> .
>>
>

2021-06-10 15:29 UTC, merged

2021-06-10 15:29 UTC, Bez625 commented
Merged