Update registry.json for AAAU1
SinglePoolAlliance/Registration pull request #311
Opened 2021-06-21 02:11 UTC by OffTheRicta

Thanks.

2021-06-21 07:29 UTC, Bez625 requested changes

2021-06-21 07:29 UTC, Bez625 commented on registry.json
> + "operatorName": "OffTheRicta",
Please change this to either your real full name, real first name or leave blank

2021-06-21 19:58 UTC, Bez625 commented
@OffTheRicta Please can you rebase this off master? I haven't been able to resolve the conflicts manually here

2021-06-22 11:37 UTC, OffTheRicta commented
> @OffTheRicta Please can you rebase this off master? I haven't been able to resolve the conflicts manually here

Not sure how to do that. Do I start again?

2021-06-22 12:00 UTC, Bez625 commented
> > @OffTheRicta Please can you rebase this off master? I haven't been able to resolve the conflicts manually here
> 
> Not sure how to do that. Do I start again?

Starting again is an option or you can follow these steps https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a . Either should work

2021-06-22 16:56 UTC, Bez625 commented
Closing this PR as new PR opened.

2021-06-22 16:56 UTC, closed without merging