Added GizmoPool
SinglePoolAlliance/Registration pull request #327
Opened 2021-06-30 14:04 UTC by jangid

2021-06-30 16:33 UTC, Bez625 requested changes

2021-06-30 16:33 UTC, Bez625 commented on registry.json
> +    "telegram": "GizmoPool",
Please can you change this to an individual TG handle and not a group or channel?

2021-06-30 16:33 UTC, Bez625 commented on registry.json
> +      "website": "https://gizmopool.com",
This website doesnt seem to work... I get an unauthorised

2021-06-30 16:33 UTC, Bez625 commented on registry.json
> +      "reddit": "GizmoPool",
This user doesnt seem to exist on reddiut

2021-06-30 16:33 UTC, Bez625 commented on registry.json
> +      "facebook": "",
Please can you add some form of social media presence? Generally people choose twitter

2021-07-02 14:25 UTC, jangid commented
I have made the suggested changes.

2021-07-05 07:43 UTC, merged