Adding Relay Stake Pool to registry.json
SinglePoolAlliance/Registration pull request #367
Opened 2021-08-02 06:03 UTC by MichaelVanStan

2021-08-14 10:01 UTC, leo42 requested changes

2021-08-14 10:01 UTC, leo42 commented on registry.json
> +        "telegram": "relaystakepool",
Please use a personal telegram handle,(No groups or pages)

2021-08-17 02:39 UTC, MichaelVanStan reviewed
altered telegram handle from stakepool to personal

2021-08-17 02:42 UTC, MichaelVanStan commented
@leo42 please see change above whereby updating telegram handle from pool's to my personal.

Please let me know if you'd like any further changes

2021-09-14 16:11 UTC, Bez625 requested changes
Please can you fix? It looks like the json validation failed

2021-09-14 18:31 UTC, MichaelVanStan commented
@Bez625 & @leo42 please see change, I've fixed the JSON format issue (apologies for that).

2021-09-24 08:42 UTC, merged