Update registry.json
SinglePoolAlliance/Registration pull request #379
Opened 2021-08-14 07:09 UTC by ThePeer

added FLOW

2021-08-14 11:03 UTC, leo42 requested changes

2021-08-14 11:03 UTC, leo42 commented on registry.json
> +       "operatorName": "FLOW pool",
Please use a real name or leave empty.

2021-08-14 12:25 UTC, ThePeer commented on registry.json
> +       "operatorName": "FLOW pool",
replaced "FLOW pool" with "Peer"

2021-08-15 07:37 UTC, Bez625 requested changes

2021-08-15 07:37 UTC, Bez625 commented on registry.json
> +
You seem to be missing a brace:

```suggestion
},
```

2021-08-15 07:38 UTC, Bez625 commented on registry.json
> +       "operatorName": "Peer",
```suggestion
       "github": ""                               
```

2021-08-15 07:39 UTC, Bez625 commented on registry.json
> +       "operatorName": "Peer",
```suggestion
       "operatorName": "Peer",  
       "github": ""                                    
```

2021-08-15 07:39 UTC, merged