Update registry.json
SinglePoolAlliance/Registration pull request #451
Opened 2021-11-03 23:09 UTC by antrixy

Added information for pool Antrix.

2021-11-06 08:56 UTC, Bez625 requested changes

2021-11-06 08:56 UTC, Bez625 commented on registry.json
> +      "twitter": "Antrix94841957",
It would be nice to see some activity on this social media account. Right now there is one post and no one following or being followed.

2021-11-06 08:56 UTC, Bez625 commented on registry.json
> +    "telegram": "Antrix",
Please can you add in the `operatorName` and `github` fields? Even if you leave them blank?

operatorName must be either blank or your real name!

2021-11-08 01:40 UTC, antrixy commented
Updated as per request

2021-11-18 14:59 UTC, Bez625 requested changes

2021-11-18 14:59 UTC, Bez625 commented on registry.json
> -    "ticker": "LOVLK",
This PR is removing LOVLK... You need to add your pool only. Ping me on CSPA Telegram if you are having trouble

2021-11-19 17:22 UTC, closed without merging

2021-11-19 17:22 UTC, antrixy commented
Merge issues.