add 5HARE pool
SinglePoolAlliance/Registration pull request #467
Opened 2021-11-21 12:23 UTC by 5pecia1

Hello.
I'm pleased to be here.

2021-11-24 18:21 UTC, Bez625 requested changes

2021-11-24 18:21 UTC, Bez625 commented on registry.json
> +    "operatorName": "5pecia1",
Please change this to be either your real full name, real first name or leave empty

2021-11-24 18:21 UTC, Bez625 commented on registry.json
> +      "youtube": ""
Please add an active social media presence

2021-12-17 08:46 UTC, Bez625 requested changes

2021-12-17 08:46 UTC, Bez625 commented on registry.json
> +      "twitter": "https://twitter.com/5HARE_Pool",
There is no activity on this account... We look for some amount of active social media presence. Also please can you make this just the twitter handle, e.g. `5HARE_Pool`

2022-01-04 04:28 UTC, 5pecia1 commented
@Bez625  Okay. Thanks your review.
After activating Twitter, I will request a PR again.

2022-01-04 04:28 UTC, closed without merging