Added Reyts Registration Details
SinglePoolAlliance/Registration pull request #470
Opened 2021-11-24 15:02 UTC by reyts

2021-11-24 15:03 UTC, reyts commented
Added Reyts Registration details

2021-11-25 07:33 UTC, Bez625 requested changes

2021-11-25 07:33 UTC, Bez625 commented on registry.json
> +    "telegram": "",
You must have a telegram handle to join the alliance. This must be the telegram of an individual and not a group or channel

2021-11-25 07:33 UTC, Bez625 commented on registry.json
> +    "operatorName": "Reyts",
Please change this to be either your real full name, real first name or leave blank

2021-12-17 08:43 UTC, Bez625 commented
If you would still like to be included please can you make the changes requested? I will close in the coming weeks if no changes are made

2022-01-11 16:17 UTC, Bez625 commented
Closing as no update for a while. If you would still like to be added to the alliance then please feel free to raise another PR

2022-01-11 16:17 UTC, closed without merging