Added DEEP to registry.json
SinglePoolAlliance/Registration pull request #474
Opened 2021-12-02 23:46 UTC by kardall

2021-12-17 08:50 UTC, Bez625 requested changes

2021-12-17 08:50 UTC, Bez625 commented on registry.json
> +    "poolId": "pool136903m0kag2amlga2ypcz8wnf7d552qgy5t6vz2pqlzuq2kyshy",
Please change this to the pool_id, e.g. 8e8af8edf6ea15ddfd1d5103811dd34f9b4a28082517a6094107c5c0

2021-12-17 08:50 UTC, Bez625 commented on registry.json
> +    "telegram": "",
You must add a telegram handle to join the alliance. This must be a TG handle of an individual and not a channel or group

2022-01-03 20:32 UTC, kardall commented
Updated Requested Conflicts

2022-01-11 16:21 UTC, merged