Adding Shiok pool
SinglePoolAlliance/Registration pull request #476
Opened 2021-12-17 07:43 UTC by shiokcardano

Thanks

2021-12-17 08:53 UTC, Bez625 requested changes

2021-12-17 08:53 UTC, Bez625 commented on registry.json
> +    "telegram": "",
You must add a telegram handle to join the alliance. This must be a TG handle of an individual and not a channel or group

2022-01-05 01:52 UTC, shiokcardano commented
Hi, I updated the telegram section and push in a new merge. Thanks.

2022-01-11 16:24 UTC, Bez625 commented on registry.json
> +   "ticker": "SHIOK"
```suggestion
   "ticker": "SHIOK",
```

2022-01-11 16:25 UTC, merged