Update registry.json with fire-pool data
SinglePoolAlliance/Registration pull request #484
Opened 2022-01-10 10:22 UTC by sephirot1024

2022-01-11 16:37 UTC, Bez625 requested changes

2022-01-11 16:37 UTC, Bez625 commented on registry.json
> +    "telegram": "fire_pool",
Please change this to be the telegram handle of an individual and not a group or channel. Thanks

2022-01-11 16:37 UTC, Bez625 commented on registry.json
>    }
Please could you add in the `github` key, even if it is blank? Thanks

2022-01-12 09:51 UTC, sephirot1024 reviewed
Everything should be nice now

2022-01-12 13:09 UTC, merged