Update registry.json
SinglePoolAlliance/Registration pull request #496
Opened 2022-01-28 14:59 UTC by HT-Moh

Add SPO 
Ticker: CCYT

2022-02-05 06:36 UTC, Bez625 requested changes

2022-02-05 06:36 UTC, Bez625 commented on registry.json
> +    "telegram": "cryptocatalyst0",
Please change this to be the handle of an individual and not a group or channel

2022-02-05 06:36 UTC, Bez625 commented on registry.json
> +    "operatorName": "HT-Moh",
Please put either your real name or leave blank

2022-02-18 16:03 UTC, HT-Moh commented
Sorry for the delay PR updated.

2022-02-20 08:10 UTC, Bez625 approved these changes

2022-02-20 08:11 UTC, merged