Update registry.json
SinglePoolAlliance/Registration pull request #520
Opened 2022-02-17 23:00 UTC by AlexMorisis

Hello,
registering Chef Pool

2022-02-18 09:20 UTC, Bez625 requested changes

2022-02-18 09:20 UTC, Bez625 commented on registry.json
> +  },
You missed the section with telegram handle, operator name and github. You dont need to fill out operator name or github, but you must have the TG handle of an individual and not a group or channel

2022-03-06 10:30 UTC, Bez625 commented
Please can you address the comments. We will close PRs that are left stale for too long

2022-03-06 22:49 UTC, AlexMorisis commented
Is there anything else you would like me to do?

2022-03-15 19:00 UTC, closed without merging