ADAreactor
SinglePoolAlliance/Registration pull request #525
Opened 2022-02-20 07:57 UTC by coincooking

2022-02-20 08:25 UTC, Bez625 requested changes

2022-02-20 08:25 UTC, Bez625 commented on registry.json
> +   "telegram": "adareactor_chat",
Please change this to be a TG handle of an individual and not a group or channel

2022-02-27 14:27 UTC, Bez625 requested changes

2022-02-27 14:27 UTC, Bez625 commented on registry.json
> +   "telegram": "adareactor_chat",
Please change this to be a TG handle of an individual and not a group or channel

2022-02-27 16:53 UTC, coincooking commented
Hello.
Please tell me how I can do that. Thank you.


вс, 27 февр. 2022 г., 16:27 Chris Berry ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In registry.json
> <https://github.com/SinglePoolAlliance/Registration/pull/525#discussion_r815446859>
> :
>
> > @@ -4425,5 +4425,20 @@
>     "telegram": "lunarpool_io",
>     "operatorName": "Dusan",
>     "github": "lunarpool"
> +  },
> +  {
> +   "ticker": "ARC",
> +   "poolId": "2fd4c1782db3cb6a97f910ca2c6f15914e2c45f75f1ca1cc168e319c",
> +   "social": {
> +     "website": "https://adareactor.com/",
> +     "twitter": "ADAreactor",
> +     "reddit": "ADAreactor",
> +     "facebook": "",
> +     "instagram": "",
> +     "youtube": ""
> +   },
> +   "telegram": "adareactor_chat",
>
> Please change this to be a TG handle of an individual and not a group or
> channel
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SinglePoolAlliance/Registration/pull/525#pullrequestreview-894509717>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW7IFUMI4LK24UAEJPX3E73U5IYEZANCNFSM5O4CLXMA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-06 09:59 UTC, Bez625 commented
For your personal telegram account go to settings -> edit profile and you will see a screenshot like below. The Username is your telegram handle. Please provide this.

![Screenshot from 2022-03-06 09-58-04](https://user-images.githubusercontent.com/4602753/156918267-a61448bd-4183-4b6a-9089-c539cfcbb0bd.png)

2022-04-03 07:54 UTC, Bez625 commented
Closing PR as no update in last month. Please raise another PR if you wish to join the alliance still

2022-04-03 07:54 UTC, closed without merging