KASH Pool
SinglePoolAlliance/Registration pull request #539
Opened 2022-02-27 02:18 UTC by Thorne128

### Commitment
    

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ x] Added a telegram handle of an **individual** and not that of a group or channel.
- [x ] Added a social media account with activity.
- [x ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [x ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ x] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-02-27 14:49 UTC, Bez625 requested changes

2022-02-27 14:49 UTC, Bez625 commented on registry.json
> +    "url_png_icon_64x64": "https://photos.google.com/photo/AF1QipND_4v5wKvI-zMj9pFzK2T2brJ5UnkDlMQmGTBZ",
These logo fields are not required or used in any way, please remove

2022-02-27 14:49 UTC, Bez625 commented on registry.json
> +    "telegram": "",
You must supply a telegram handle of an individual and not a group or channel

2022-02-28 00:53 UTC, Thorne128 reviewed
changes made

2022-02-28 10:37 UTC, closed without merging