Update registry.json
SinglePoolAlliance/Registration pull request #570
Opened 2022-04-04 00:18 UTC by thinkgrowcrypto

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-04-04 07:06 UTC, Bez625 requested changes

2022-04-04 07:06 UTC, Bez625 commented on registry.json
> +    "telegram": "https://t.me/stakepool_21ADA",
This needs to be your telegram username, it can be found under the settings -> profile -> username section of your telegram app

2022-04-04 07:06 UTC, Bez625 commented on registry.json
> +      "twitter": "https://twitter.com/thinkgrowcrypto",
Please can you remove the https://twitter.com/ part? Similarly with Insta

2022-04-26 14:02 UTC, Bez625 commented
Please can you address the comments? If not we will look to close in the coming weeks.

2022-04-26 16:45 UTC, thinkgrowcrypto commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0in;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->For Twitter, insta & telegram you want the usernames only, correct? Think & Grow Crypto From: Chris BerrySent: Monday, April 4, 2022 12:07 AMTo: SinglePoolAlliance/RegistrationCc: thinkgrowcrypto; AuthorSubject: Re: [SinglePoolAlliance/Registration] Update registry.json (PR ***@***.*** requested changes on this pull request.In registry.json:> @@ -1,4 +1,17 @@ [{+    "ticker": "21ADA",                                                       +    "poolId": "f3efb842c77895dde51e95e54d9c309da599631ef31216bcfea11083", +    "social": {       +      "website": "https://21ada.ca",+      "twitter": "https://twitter.com/thinkgrowcrypto", +      "instagram": "https://www.instagram.com/thinkgrowcrypto/",+      "youtube": "https://www.youtube.com/channel/UC2DcLdAPKAwo66JbcI-0w0Q"+    },+    "telegram": "https://t.me/stakepool_21ADA",                                          This needs to be your telegram username, it can be found under the settings -> profile -> username section of your telegram appIn registry.json:> @@ -1,4 +1,17 @@ [{+    "ticker": "21ADA",                                                       +    "poolId": "f3efb842c77895dde51e95e54d9c309da599631ef31216bcfea11083", +    "social": {       +      "website": "https://21ada.ca",+      "twitter": "https://twitter.com/thinkgrowcrypto", Please can you remove the https://twitter.com/ part? Similarly with Insta—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2022-05-01 08:04 UTC, Bez625 commented
>  -->For Twitter, insta & telegram you want the usernames only, correct? Think & Grow Crypto From: Chris BerrySent: Monday, April 4, 2022 12:07 AMTo: SinglePoolAlliance/RegistrationCc: thinkgrowcrypto; AuthorSubject: Re: [SinglePoolAlliance/Registration] Update registry.json (PR ***@***.*** requested changes on this pull request.In registry.json:> @@ -1,4 +1,17 @@ [{+    "ticker": "21ADA",                                                       +    "poolId": "f3efb842c77895dde51e95e54d9c309da599631ef31216bcfea11083", +    "social": {       +      "website": "[https://21ada.ca",+](https://21ada.ca%22,+)      "twitter": "https://twitter.com/thinkgrowcrypto", +      "instagram": "[https://www.instagram.com/thinkgrowcrypto/",+](https://www.instagram.com/thinkgrowcrypto/%22,+)      "youtube": "[https://www.youtube.com/channel/UC2DcLdAPKAwo66JbcI-0w0Q"+](https://www.youtube.com/channel/UC2DcLdAPKAwo66JbcI-0w0Q%22+)    },+    "telegram": "https://t.me/stakepool_21ADA",                                          This needs to be your telegram username, it can be found under the settings -> profile -> username section of your telegram appIn registry.json:> @@ -1,4 +1,17 @@ [{+    "ticker": "21ADA",                                                       +    "poolId": "f3efb842c77895dde51e95e54d9c309da599631ef31216bcfea11083", +    "social": {       +      "website": "[https://21ada.ca",+](https://21ada.ca%22,+)      "twitter": "https://twitter.com/thinkgrowcrypto", Please can you remove the https://twitter.com/ part? Similarly with Insta—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

It's a little difficult to read your replies on github...

Yes if you could amend to have only usernames and not full links that would be great

2022-05-19 10:00 UTC, Bez625 commented
Please address the comments. I will look to close over the coming days if there are no updates

2022-05-20 19:25 UTC, Bez625 commented on registry.json
> +      "youtube": "https://www.youtube.com/channel/UC2DcLdAPKAwo66JbcI-0w0Q"
```suggestion
      "youtube": "https://www.youtube.com/channel/UC2DcLdAPKAwo66JbcI-0w0Q",
      "facebook": ""
```

2022-05-20 19:26 UTC, merged