Update registry.json
SinglePoolAlliance/Registration pull request #572
Opened 2022-04-08 19:47 UTC by CarPoolCrypto

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-04-26 13:21 UTC, Bez625 requested changes

2022-04-26 13:21 UTC, Bez625 commented on registry.json
> +    "telegram": "",
You must add the telegram username of an individual and not a group or channel

2022-05-19 09:59 UTC, Bez625 commented
Please address the comments. I will look to close over the coming days if there are no updates

2022-05-20 03:18 UTC, CarPoolCrypto commented
Sorry for the long delay, thank you for reaching out again. I don't have a lot of experience with github. I hope that resolves everything.

2022-05-20 16:14 UTC, Bez625 approved these changes

2022-05-20 16:16 UTC, merged