Update registry.json
SinglePoolAlliance/Registration pull request #584
Opened 2022-05-03 01:06 UTC by pittengermd

Added TFSF info

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-05-03 01:09 UTC, pittengermd commented
Added TFSF info to registration.json

2022-05-19 09:14 UTC, Bez625 requested changes

2022-05-19 09:14 UTC, Bez625 commented on registry.json
> +    "telegram": "freespeechforum",
The value for this should be the username of an individual and not a group or channel. Please change

2022-06-11 09:59 UTC, Bez625 commented
Please address the comments or I will look to close in the coming days. Thanks

2022-08-13 10:52 UTC, Bez625 commented
Closing as no updates. Please feel free to raise a new PR if you still wish to join

2022-08-13 10:52 UTC, closed without merging