Update registry.json
SinglePoolAlliance/Registration pull request #608
Opened 2022-05-21 09:48 UTC by dinoaus

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-05-27 14:51 UTC, Bez625 requested changes

2022-05-27 14:51 UTC, Bez625 commented on registry.json
> +   "telegram": "",
You must provide a telegram username of an individual and not a group or channel

2022-06-11 10:07 UTC, Bez625 commented
Please address the comments or I will look to close in the coming days. Thanks

2022-06-11 10:31 UTC, dinoaus commented
> Please address the comments or I will look to close in the coming days. Thanks

Should be fixed.

2022-07-11 15:01 UTC, merged