Adding_SAPIO registry.json
SinglePoolAlliance/Registration pull request #613
Opened 2022-05-23 11:29 UTC by nikolas835

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-05-27 14:58 UTC, Bez625 requested changes

2022-05-27 14:58 UTC, Bez625 commented on registry.json
> +	"telegram": "Sapiopool",
Please change this to be the telegram username of an individual and not a group or channel

2022-05-27 14:58 UTC, Bez625 commented on registry.json
> +		"twitter": "nikos_SAPIO",
Looks like this account doesnt exist

2022-05-27 18:00 UTC, nikolas835 commented
I've changed that now, had them reversed.
Thanks

On Fri, 27 May 2022 at 15:58, Chris Berry ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In registry.json
> <https://github.com/SinglePoolAlliance/Registration/pull/613#discussion_r883695792>
> :
>
> > @@ -5096,5 +5096,18 @@
>     "telegram": "wafflepool",
>     "operatorName": "",
>     "github": ""
> - }
> + },
> + {
> +	"ticker": "SAPIO",
> +	"poolId": "c3cd2527a5f0b82a86ff69fdd5a3440dc51bcb957953ba19137738c0",
> +	"social": {
> +		"twitter": "nikos_SAPIO",
> +		"facebook": "",
> +		"instagram": "",
> +		"youtube": "https://www.youtube.com/channel/UCcPH2RMsszRGJ2awvLdMKzQ"
> +	},
> +	"telegram": "Sapiopool",
>
> Please change this to be the telegram username of an individual and not a
> group or channel
> ------------------------------
>
> In registry.json
> <https://github.com/SinglePoolAlliance/Registration/pull/613#discussion_r883696215>
> :
>
> > @@ -5096,5 +5096,18 @@
>     "telegram": "wafflepool",
>     "operatorName": "",
>     "github": ""
> - }
> + },
> + {
> +	"ticker": "SAPIO",
> +	"poolId": "c3cd2527a5f0b82a86ff69fdd5a3440dc51bcb957953ba19137738c0",
> +	"social": {
> +		"twitter": "nikos_SAPIO",
>
> Looks like this account doesnt exist
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SinglePoolAlliance/Registration/pull/613#pullrequestreview-987628855>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYIY3PE46QJEAGCS24JECUTVMDPKFANCNFSM5WVQPUWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-29 12:46 UTC, merged

2022-05-30 07:16 UTC, nikolas835 commented
Awesome, thanks!

On Sun, 29 May 2022 at 13:46, Chris Berry ***@***.***> wrote:

> Merged #613 <https://github.com/SinglePoolAlliance/Registration/pull/613>
> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SinglePoolAlliance/Registration/pull/613#event-6698254638>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYIY3PE7LH4SGUWO2HRBUHTVMNRJNANCNFSM5WVQPUWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>