Adding COINZ
SinglePoolAlliance/Registration pull request #635
Opened 2022-06-12 05:56 UTC by cxhercules

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-07-11 15:22 UTC, Bez625 requested changes

2022-07-11 17:44 UTC, cxhercules commented on registry.json
> +    "telegram": "adacoinz_chat",
Update made.

2022-07-28 15:03 UTC, cxhercules commented
@Bez625 I have made changes you requested

2022-08-13 10:58 UTC, Bez625 approved these changes

2022-08-13 10:58 UTC, merged