Create skull_pool
SinglePoolAlliance/Registration pull request #664
Opened 2022-08-29 02:42 UTC by diicasses

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-08-30 07:54 UTC, Bez625 requested changes

2022-08-30 07:54 UTC, Bez625 commented on skull_pool
> +{
This should be added to the `registry.json` file

2022-09-13 13:35 UTC, Bez625 commented
Please address the comments or I will look to close over the coming weeks.

2022-09-13 14:12 UTC, diicasses reviewed
Looks good, sorry im a noob with github.

2022-09-20 07:48 UTC, closed without merging