Added Falcon Stakepool
SinglePoolAlliance/Registration pull request #666
Opened 2022-08-30 02:29 UTC by MatiFalcone

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2022-09-13 13:36 UTC, Bez625 requested changes

2022-09-13 18:39 UTC, MatiFalcone commented on registry.json
> + "telegram": "FalconStakepool",
Updated.

2022-09-13 18:39 UTC, MatiFalcone commented on registry.json
> + "operatorName": "Falcon",
Updated.

2022-09-20 07:27 UTC, Bez625 approved these changes

2022-09-20 07:29 UTC, merged