Update registry.json - adding OANDB pool
SinglePoolAlliance/Registration pull request #725
Opened 2023-02-02 14:32 UTC by Bhugaboo

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2023-02-02 14:33 UTC, Bhugaboo commented
Adding OANDB pool

2023-02-05 09:36 UTC, Bez625 requested changes

2023-02-05 09:36 UTC, Bez625 commented on registry.json
> +    "poolId": "pool1mt3edrc94lwwragf223w8nx5mfs20qpvtzx2asgjz3jm7sd2qax",
Please replace with the pool hex id and not bech32

2023-02-06 01:57 UTC, closed without merging

2023-02-06 03:07 UTC, Bhugaboo commented
Thanks, have updated the to use the hex id

From: Chris Berry ***@***.***>
Sent: Sunday, February 5, 2023 4:36 AM
To: SinglePoolAlliance/Registration ***@***.***>
Cc: Bhugaboo ***@***.***>; Author ***@***.***>
Subject: Re: [SinglePoolAlliance/Registration] Update registry.json - adding OANDB pool (PR #725)


@Bez625 requested changes on this pull request.

________________________________

In registry.json<https://github.com/SinglePoolAlliance/Registration/pull/725#discussion_r1096652405>:

> @@ -5403,5 +5403,19 @@

     "telegram": "caikejungle",

     "operatorName": "Carlos Souza",

     "github": "wowica"

+  },

+  {

+    "ticker": "OANDB",

+    "poolId": "pool1mt3edrc94lwwragf223w8nx5mfs20qpvtzx2asgjz3jm7sd2qax",

Please replace with the pool hex id and not bech32

—
Reply to this email directly, view it on GitHub<https://github.com/SinglePoolAlliance/Registration/pull/725#pullrequestreview-1284173578>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGI5RLRCUTQ2OLDBAWBMYYDWV5YBLANCNFSM6AAAAAAUPDIVEU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>