Adding jaguares pool to registry.json
SinglePoolAlliance/Registration pull request #733
Opened 2023-02-13 20:38 UTC by Danvegamo

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2023-02-15 16:56 UTC, Danvegamo commented
I'm waiting for approval

2023-02-16 18:54 UTC, Bez625 requested changes

2023-02-16 18:54 UTC, Bez625 commented on registry.json
> +   "instagram": "@jaguares_pool",
Please remove the @

2023-02-25 08:03 UTC, Bez625 requested changes

2023-02-25 08:03 UTC, Bez625 commented on registry.json
> +   "instagram": "jaguares_pool",
Please can you add some social media activity? The instagram account seems empty...

2023-03-24 10:42 UTC, Bez625 commented
Please address the comments or I will look to close in the coming weeks

2023-04-10 07:40 UTC, Bez625 commented
Closing as there have been no updates since changes were requested. Feel free to raise another PR if you still want to join

2023-04-10 07:40 UTC, closed without merging