Adding RTIST
SinglePoolAlliance/Registration pull request #735
Opened 2023-02-16 18:44 UTC by RTISTpool

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Not added a telegram handle because I do not use telegram.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2023-02-16 18:57 UTC, Bez625 requested changes

2023-02-16 18:57 UTC, Bez625 commented on registry.json
> +    "telegram": "None",
You must have a TG handle to join

2023-02-16 19:00 UTC, RTISTpool commented
I use Discord, not Telegram. If that disqualifies the pool entirely based on a social media platform then so be it I guess, that’s a centralised decision. We’ll still be here supporting decentralisation.


> On Feb 16, 2023, at 13:57, Chris Berry ***@***.***> wrote:
> 
> 
> @Bez625 requested changes on this pull request.
> 
> In registry.json <https://github.com/SinglePoolAlliance/Registration/pull/735#discussion_r1108903383>:
> 
> > @@ -5477,5 +5477,20 @@
>      "telegram": "BalanceAnalytics",
>      "operatorName": "",
>      "github": "Balance-Analytics-io"
> -  }
> +  },
> +  {
> +    "ticker": "RTIST",
> +    "poolId": "0df0f6e5a3191520aa0a58268c38fe608d1d931766fc006635f3f2b1",
> +    "social": {
> +      "website": "https://rtistpool.carrd.co",
> +      "twitter": "RTIST_ADAPool",
> +      "facebook": "",
> +      "discord": "",
> +      "instagram": "",
> +      "youtube": ""
> +    },
> +    "telegram": "None",
> You must have a TG handle to join
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/SinglePoolAlliance/Registration/pull/735#pullrequestreview-1302101067>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A346EXAFRIZ7IT2PGIDHXRTWXZ2CVANCNFSM6AAAAAAU6RCRJQ>.
> You are receiving this because you authored the thread.
>

2023-02-25 07:54 UTC, Bez625 commented
> I use Discord, not Telegram. If that disqualifies the pool entirely based on a social media platform then so be it I guess, that’s a centralised decision. We’ll still be here supporting decentralisation.

Ok I'll close the ticket. If you want to come back with a less passive aggressive attitude and have a productive discussion then we're always willing to talk.

2023-02-25 07:54 UTC, closed without merging