CCCC Pool Update registry.json
SinglePoolAlliance/Registration pull request #766
Opened 2023-05-02 17:21 UTC by CharityDA0

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2023-05-17 17:23 UTC, leo42 requested changes

2023-05-17 17:23 UTC, leo42 commented on registry.json
> + "telegram": "Cardano Community Charity Coin",
This is not a valid Telegram handle

2023-05-18 03:03 UTC, CharityDA0 commented
I've updated telegram info

2023-05-25 10:47 UTC, leo42 approved these changes

2023-05-25 10:47 UTC, merged