Adding WAX Update registry.json
SinglePoolAlliance/Registration pull request #780
Opened 2023-07-09 20:15 UTC by DrSicks

### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [ ] Added a telegram handle of an **individual** and not that of a group or channel.
- [ ] Added a social media account with activity.
- [ ] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [ ] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [ ] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

2023-08-09 11:58 UTC, leo42 requested changes

2023-08-09 11:58 UTC, leo42 commented on registry.json
> +   "poolId": "pool1vurlp3ndgge8avz3h8lu2wzdqcwc8w4l5s43rzlk8p4pz0x5vla",
Pool Id is wrong, in HEX format WAX pool is :

6707f0c66d42327eb051b9ffc5384d061d83babfa42b118bf6386a11

2023-08-28 11:53 UTC, Bez625 commented
@DrSicks please address the comments or we will look to close in the coming weeks.

2023-11-17 15:22 UTC, leo42 requested changes

2023-11-17 15:22 UTC, leo42 commented on registry.json
> +   "telegram": "Alejandro",
Please use a personal telegram handle

2025-01-23 09:08 UTC, Bez625 commented
Closing as no update in 18 months. Please feel free to address the review comments and re-raise

2025-01-23 09:08 UTC, closed without merging